spring.application.name=tcg-trader

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/tcgtrader?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080

# Security / JWT
security.jwt.secret=change-me-change-me-change-me-change-me-64bytes-minimum-please
security.jwt.expiration-ms=86400000

# Logging (temporary — for JWT filter + security diagnostics)
logging.level.com.tcgtrader.security.JwtAuthenticationFilter=DEBUG
logging.level.org.springframework.security=DEBUG


#mail 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuemail@gmail.com
spring.mail.password=TU_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
